### ISSUE TITLE
Error 8800 Photoshop 2021

### ISSUE THREAD

**Issue by JuliaF1988** [kavindupasan/batch-bg-remover-photoshop#1]
Hello,
when I try to run the script I get the Error 8800 (general Photoshop error) on line 44: app.open(FileList[a]);
<img width="413" alt="image" src="https://user-images.githubusercontent.com/25012259/110624422-7a345d00-819e-11eb-95ef-6168e8943353.png">
I use Photoshop 2021

**Comment by kavindupasan** [comment]
Need more details to determine what's the real error. Can you submit folder paths of src and out folders?

**Comment by JuliaF1988** [comment]
var sourceFolder = Folder("C:\\3DScan\\mitHintergrund");
var saveFolder = new Folder("C:\\3DScan\\ohneHintergrund");

The only other change is:
var isTransparent = false;

**Comment by kavindupasan** [comment]
Try with escaping backslash in path. 
Use `Folder("C:\3DScan\mitHintergrund")` instead of `Folder("C:\3DScan\mitHintergrund")`

**Comment by kavindupasan** [comment]
This issue will be marked as closed in 3 days from now due to inactivity.

**Comment by JuliaF1988** [comment]
Hello, still the same Problem. Actually I used double Backslash already. Github replaced it because I didn't use the "code" tag.
```
var sourceFolder = Folder("C:\\3DScan\\mitHintergrund")
var saveFolder = new Folder("C:\\3DScan\\ohneHintergrund");
```

**Comment by JuliaF1988** [comment]
Hello, with the updated script the error persists. I will contact you via email for a screen sharing.

**Comment by TheSevDev** [comment]
I had the same issue I think. Two errors actually:

**Error 1302**
Line: 35
var doc_bg = app.activeDocument;

Solution: Make sure to have a file open in PSD before launching the script (File > New)

**Error 8000**
Line: 56
app.open(fileList[a]);

Solution: Uncomment line 46
`var fileList = sourceFolder.getFiles(/\.(jpg|png|tif|psd|crw|cr2|nef|dcr|dc2|raw|heic)$/i);`

The errors above occured with the newest script (v2) and two PSD versions (21.2.6, 22.0.1)

**Comment by kavindupasan** [comment]
@JuliaF1988 , @TheSevDev 's solution should work for you.

**Comment by JuliaF1988** [comment]
yes, you are right. Thanks for your help :)
